hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "036bd1f08a582f2a38809e3ab65720d5e04d84fcc1c7b8558d6888c319e18527"
metafile = true

[[files]]
file = "mods/caduceus.pw.toml"
hash = "bc10528b0f0b0308bc4bfb1eb6c15451da406f28c8d95ed7b3d111820d5fc108"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/complex-hex.pw.toml"
hash = "7deff0eada2fe367cf5d47b8f48ace87d6af8baa4044b1e1be0491d9088bb866"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e81c635602878f92af9a9c11b92481b25c7aaf3f68cd015dabf5f67201886401"
metafile = true

[[files]]
file = "mods/efhexs-1.0.0-20dbe0d.jar"
hash = "bdbea2df3c466eff733377685a4a199516f7ac7b67c82dd32e0521d37f386bce"

[[files]]
file = "mods/emi.pw.toml"
hash = "fec1ffa03b4d62e47be25512840490844fc383cf82d2ad35345b2f87a21e8228"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/ephemera-fabric-1.20.1-0.3.0.jar"
hash = "1d385e8fa6bf1d33fd76b89cddab3f51545261bac924092b58193324b2a82671"

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/female-gender.pw.toml"
hash = "26c33cf9892d2221149aa0fb26eb1dbb17227f7a3f4542624a40ab69dfea60c4"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4449401b59481016fa2a66d6e749795129160cb1ab3e7932e15033c6b5815455"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
hash = "61e5f0c2fc067877744d9cdbed9704e4da4933a4be893e5ef61174346fb13af6"
metafile = true

[[files]]
file = "mods/hex-machina.pw.toml"
hash = "6a0af715b6a087f28f3a440f18b73b87786ef293a475c186659b7b5eac10ffa3"
metafile = true

[[files]]
file = "mods/hexal.pw.toml"
hash = "3e51d9ad93efb292181f8960816a58707ae28841c310b77c28721ac7039931d1"
metafile = true

[[files]]
file = "mods/hexcassettes.pw.toml"
hash = "39e27b12d6b188df2b249bf84ed8427c62a7d9c9802ab0469304d554f89f43be"
metafile = true

[[files]]
file = "mods/hexcellular.pw.toml"
hash = "51c39678a509b311fe444e1231843d152157136297d83f52c41d19e85a17d790"
metafile = true

[[files]]
file = "mods/hexchanting.pw.toml"
hash = "551b3d384d4bbb2915a75b1e9e94ced6121643a1cec9186887859a6eee1e251a"
metafile = true

[[files]]
file = "mods/hexdebug.pw.toml"
hash = "b48832001c692143d8140577323ec8033bfe868c44d79daa27cdd8a64913cf40"
metafile = true

[[files]]
file = "mods/hexgender.pw.toml"
hash = "5c00a6d637f656ec5386b039db2271b0433f79ef137d2c29cd95279a618b737b"
metafile = true

[[files]]
file = "mods/hexical.pw.toml"
hash = "353bc9603d4bfa25ce7e2e15a1a8cf34f6ab18695cdafd8c4e0d351e841ac157"
metafile = true

[[files]]
file = "mods/hexparse.pw.toml"
hash = "e2f55b29e52f10afad1832703d1092e83e029c1f79a2a2b22d9c1a8bf920aedc"
metafile = true

[[files]]
file = "mods/hexpigmentplus.pw.toml"
hash = "6f1ece0609f0bb13793aafafbb0297f7acda122542c3992a131676ca139b4de4"
metafile = true

[[files]]
file = "mods/hexportation.pw.toml"
hash = "b5ed3b3b787b8cda46501f21bf1b7a1366a81a1ca64f87892e909eff19c15a56"
metafile = true

[[files]]
file = "mods/hexpose.pw.toml"
hash = "a3679744d85237d364e432d07acc54775ef0ab10c80c542c5d5fb5d683dc43d6"
metafile = true

[[files]]
file = "mods/hexstruction.pw.toml"
hash = "140d22763aea94ff764113060519f5998e1ff1a980cb85c312115b2c012e1c74"
metafile = true

[[files]]
file = "mods/hexthingy.pw.toml"
hash = "a12033b30bacf51de49b79599cf4d02591bbdac978f14a6a8b4b245e718f52da"
metafile = true

[[files]]
file = "mods/hexxyattributes.pw.toml"
hash = "796a322e8832c389de5c5b0f810d27022aec62404c265506f9c1bf04d990251e"
metafile = true

[[files]]
file = "mods/hierophantics.pw.toml"
hash = "04b60c1af307fe868c98b0e4ef4d641dbf4ebe800524ea5ad779b47cedd3ff1c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "060c6baaec85f47ba4bc2c0f4b8642b9933c27d3c166eb00ef86b4bbfd7f34a3"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/ioticblocks.pw.toml"
hash = "85412f19eccc9b4caa6932122e5e3c7b05aba22686b8cde137a96537d23ff322"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "211d05efd962f20f4eb4704ae6f781960f7931abb687e14b42fead9c980e7a95"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "ead6f125d759a3bc5892416204319369836742556943d5fed6220dbdb8f32913"
metafile = true

[[files]]
file = "mods/lapisworks.pw.toml"
hash = "61f75e922c00ab017fbc2d371b079e0493ada621b8fcf90619244bc8c25cd2ba"
metafile = true

[[files]]
file = "mods/lesser-teleport.pw.toml"
hash = "2ae602e2ec5d87e68790326913202b71da20c7166cd70beb42405412decff16b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "b66a3d19ffb4c3c122f3844421dee04acbcf1a7a6fadb277ea803ca9dd96e4b5"
metafile = true

[[files]]
file = "mods/markdownmanual.pw.toml"
hash = "887656197aff2cd6009a0ff04996b4318aa202b8ed253650860f4882a60bc876"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f43c82e3cc6079291ddae81445c703905b6c670dd43f444e47f5cd817944e822"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "200d34b575b506ab0503f7856cdcd4cc38030c27e0749e36f6bbe62cbeb16cec"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
hash = "6757363eeff33967a7beb9782d833cd9f23486933a88373e576a3856fbbaf1bd"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/neepmeat.pw.toml"
hash = "67b973f3640c8ab7cdc6f69cdc919e87487c97af2975dc8714e41c296d32d8dd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/oneironaut-fabric-1.20.1-0.5.0-8143784.jar"
hash = "4b246fb6e3e82bf03a5cd3e6eefa93784118bdcaeba1c6a26fd697f7d9f9e988"

[[files]]
file = "mods/overevaluate-1.0.0-7ebb76e.jar"
hash = "01e98745137398e905e5da6ce53e5dc8140e30480c4f27dc99db7fc991cc7c0a"

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
hash = "49ef3ff0a74c6338f2160c4ee683ae34f745a38c0c87f2d7527e4f88406113fe"
metafile = true

[[files]]
file = "mods/phlexiful.pw.toml"
hash = "6c12c8bf3a6b4ce0eff470be2941afead60953d23a09152d0e0c54c1bad4ed1f"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "82c3a531c2180cd45f59e433315e31dc886c464a05ea38ea0b82ce1bc033c520"
metafile = true

[[files]]
file = "mods/scryglass-1.0.0-6c096fb.jar"
hash = "9885b852bbb9d706f5a183597b701ae2ff9350cb0d6dcd24c83c7c5cb82104dc"

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/slate-works.pw.toml"
hash = "1a933ea3ce8485a9fb4a50efb5780a126e38e21ad92e03593bf987a495a8eed6"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "83cf89128bfc6d4a5d1da20565e461f89183127d5960935c1f783ba38b0cb53c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "19eeb8e2d15198628ae414184131017d7b91fa322abef285eccefa573754e3d2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3135bb6ec401e951d248de79dbdf40608e362e64b89fe9e7d2e74399f3b49375"
metafile = true

[[files]]
file = "mods/tis3d.pw.toml"
hash = "f51450fce6c7064ac1ad3d2107f0223ea0601fb9ea5e970d1cdab340464ce8b8"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "fd725a2383164ee2866a41635b0a8baf4cc1506d33df1ce1cc1455ab98a32e01"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7598f0435251f845fdf85c8ed2ac612b2d0404e0ee73a1fcdebaf4eb6c95296d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "unsup.ini"
hash = "86af55c3493eb850fbf8a611dd24d227e8672ff27ba0c202e3f0c7b1eeb8bc24"
