name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e68b84d12820d7ec18b46e1c4b8c803413fc50a2e9922d2c56328f9ac35d322"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
