name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e884139d8b2ec98961f773cbe76fae0fd04c13270990f42f8d4a4d4ec74c67c"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
