name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deb6940c066909c991099e450705bdabb8dab683e8b7c947af7b89a2c7eff9a0"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
