name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81748f06b35ea811eff0526e6323f76a545f2435ebedb66fd11a10daf91beea6"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
