name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2777ef19726fa65d5fce6103332d2cb03671906f58505b8f795be7379936e24"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
