name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "911bb05c6ce5cf66a962f81e3e9abef70afe17c9d67d59b2a17ed46ed9e033a4"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
