name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f58b571de8e5c6d260c6f94137231c4a68dabfaf712bbe487122fe93455f0ab"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
