name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb8e183ed9ffa8760f25e4548dce2c50239c9c32e568c3415adcc30297ea791e"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
