name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "189a92c1494a1a52a1c6a4f5b337c21c229f1e846c8e4b3aeab99fef72d431e4"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
