name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d390211367962dd4534d6215b8a97ff23739d035f95fff69c9afcda0efc81f7e"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
