name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a080aeac8efcfc3c634c1241cef4095561dd29ed1775b63c1f033c3f6b99a8b3"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
