name = "Magic Meat"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5917af13788d31557c957263bd92146fc41e406f9dd1ec19185e0a17a96e6391"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
