name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de94e5b7b0efde7685e62ff9b816b7842e7fd8b07dff05940482d05e0a045b05"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
