name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d68a6622cb40eda37c9d8aa1fc36d97c6205edfb973b26d802abb5755fe7ae8b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
