name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b40c7c0e5a5b90a5d7500742e99492ff6ddd87ff9347da2a60f5cfef3cc9971b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
