name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d5a211a46370548880e219c60e560d7963de9483184731d1642edf144dfc4fe"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
