name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67df2db6fbf9c9dc9e2171721d89a949fbc46117e65dda5d1caf03f8c904d6c2"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
