name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "897bfddd5bacc63040d24f295816c655d14ef240963eb38f2ccb669ec65bd491"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
