name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "413f5ea35c2ee5a67f073b75bae2073ad4a37b9703f978c3fb082b6e4a19c9aa"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
