name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5cb4d2d5684f685dc4be57fe5aa2803f58470983315b4be59f2f5892e7c4d45"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
