name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a65a6d0b8da48850f2ce16e04cb0084d328b16babb83dbbb824d6a40561e968"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
