name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad7515949d3cc32ad715013f3225ba52934aa94a1f505ea78bb81c485eb97e9f"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
