name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21f5cc2a30e3f7303f117fa54adb771f052efc98e11d494fc377c34896321ab0"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
