name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e455cc998b34f120d92d315d7614955ae2c4e38e8085c20e0159e7243cd380e0"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
