name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05f6bc963bd6f042ec88aa6eae74effcf5d168d7aae6b98700fbbcae96747105"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
