name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dacbebe55eace7f83742b5fb69e180de4e1e99921e8590a279b3c71fb1bb95d"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
