name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "358ce40d471c337b8d3489dc400bf9500bdd6320c517120ff448b04d3954507f"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
