name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20d81f617bfce92331f2b2b7ff3618d7905eb986fe2a012addf86f3e572cf315"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
