name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6213c7f46d80ebc334b30473202a4dbfd04335c40ee5bd5b42d9b12a302ec22d"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
