name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daefbe0b63af1ef3d6c107f69d07f5b88690ec4c2fc92913386ed156fdbbb372"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
