name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "745caae7a9a2a62ab74c9e39d30a1659a971dec0669974be48a962d608e2dcdb"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
