name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d1d08e5bab7641cfd4f8df177ce3512014162462765bdee174fdf8358b40e37"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
