name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cfdbb292f22f414631faecbcb2a3ec761bddfa9f0aa94848dd8be0eb711f4e0"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
