name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fe8bec185aefa85bed83204804fdbd37751c01ed7ca9919876c9230696d661f"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
