name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5bb3d2254cd6d35b25fb662addb26c3c9ee42cc5ef003f517b43b7931dcf74b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
