name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "452d43854e84bde1cbf84d9d48056e056b9001062f18bde878e4e4941b72b097"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
