name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32930dd0d92b0554055a46a63f96ad1eba36f320d120c24c4f84b7bb75ec7d19"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
