name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ab08a014fb06a2f5e102557024da780c6ed4b43d3248dc399b0805aee3a912b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
