name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4025a9f9f4b3981c0b9316fc39a9b3642d763a41918338539b47ea6d51520fe0"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
