name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544a88d1e00320428265dca15a0607d1ffc2d1ab4df11f422000532f88b9074a"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
