name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33b39eda6091b457c6854180c1a4f6b7f89a13e90c59c29250ed958660d9dc58"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
