name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c4d4f6c4bfc69c1bb956b4e358ea24286ac84ea564fc0a22d7396549cb3b541"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
