name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aef1d9f2e45abd7686d765ac352be92d6bd0e58f8721fa280f0c3c51cf3e9844"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
