name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f452467a60258354fa289cd6b996a2d4b14783b58b28deed37312383a53a3c0c"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
