name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b341d0c10531d4ee68cb57714300d8d1b314f85b6489362a22322f0cd870a87a"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
