name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "830cb09b835e9cb349218770ebe1ec5a0d45cec4388a745e7e46518dbe7a3435"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
