name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab0aade4f0382f02bc68b9d70f5ad617d1d0e7775bbc4b7290bd8db885e6b6b9"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
