name = "Magic Meat"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25f186d7e79011c4dd9d113c207e2ec1e8ee49954e58b0ca28c9b5c8599312d4"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
