name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9db581da63e141b3774f6c59d625f2bc9a7823bc3df4527aa14b57f12b1c35aa"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
