name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d14f0fdf1b4fe2493dc82b928dec94a6e79b675316f979f5b73894dcdbaa318a"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
