name = "Magic Meat"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bfd8ad216c049fe966a3b496c7e4943fae9febce0f719ada4e1de5d509cff4b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
