name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "954e22da68c71428bdf7f40138d2e5c936299e3ed8004d9fafa4070ed50da865"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
