name = "Magic Meat"
author = "P1x3l101"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41f84288f8df2190618dde6244e251eeb925054861cb664afced0951f7a89d5b"

[versions]
fabric = "0.18.0"
minecraft = "1.20.1"
