# If true, the Meatgun's ammo counter will be rendered on the item model instead of in the hud.
# Set to false if transparency issues occur.
# default: true
meatgunAmmoOnModel = true

[ore_fat]
	# Rendering ore fat yield when not overridden in JSON
	# default: 1.333
	defaultRenderingYield = 1.333
	# Trommel ore fat yield when not overridden in JSON
	# default: 1.5
	defaultTrommelYield = 1.5

[motors]
	# Maximum power that can be transferred by a basic motor (eJ/t)
	# default: 400
	basicMotorMaxPower = 400
	# Maximum power that can be transferred by an advanced motor (eJ/t)
	# default: 800
	advancedMotorMaxPower = 800
	# Maximum power that can be transferred by a large motor (eJ/t)
	# default: 2000
	largeMotorMaxPower = 2000

[large_compressor]
	# Droplets per unit energy per tick (droplets/eJ/t)
	# default: 400
	powerToDroplets = 400

[charnel_pump]
	# Minimum power required to run (eJ/t)
	# default: 500
	minPower = 500
	# Air consumed per unit energy (droplets/eJ/t)
	# default: 100
	powerToAir = 100

[pylon]
	# Maximum angular speed of the Pylon (???)
	# default: 40.0
	maxSpeed = 40.0
	# Angular speed at which the Pylon begins working (???)
	# default: 16.0
	runningSpeed = 16.0

[feeding_trough]
	# Amount of feed used to breed two animals (droplets)
	# default: 13500
	useAmount = 13500
	# Amount of animal feed added per gland potato (droplets)
	# default: 6750
	feedPerItem = 6750

[verrucous_stone]
	# Energy generated per Verrucous Stone block per tick (eJ/t)
	# default: 10
	passiveCoefficient = 10

[living_machines]
	# Maximum number of blocks that can be part of a single living machine
	# default: 128
	maxBlocks = 128

[power_flower]
	# Energy generated per Power Flower surface block per tick (eJ/t)
	# default: 10
	solarCoefficient = 10
	# Maximum number of blocks that can be part of a single Power Flower
	# default: 160
	maxBlocks = 160

