maximumSendSize = 10240
maximumInterSendSize = 10240
maximumRecvSize = 10240
matrixMaxArea = 10240
rateLimitChargePerTick = 1.0
rateLimitMaxValue = 8.0
interSendCostMultiplier = 2.0
sendFilterMode = "Block"
sendFilter = []
interSendFilterMode = "Block"
interSendFilter = []
recvFilterMode = "Block"
recvFilter = ["hexcasting:list"]
